[package]
name = "fate-program"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "fate"

[features]
default = []
no-entrypoint = []
dev-randomness = []

[dependencies]
fate-api.workspace = true
solana-program.workspace = true
steel.workspace = true

[dev-dependencies]
solana-program-test = "=2.1.15"
solana-sdk = "=2.1.15"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
